### ISSUE TITLE
TC版本的有部分沒改變

### ISSUE THREAD

**Issue by ghost** [NightFurySL2001/WD-XL-font-deprecated#1]
其中TC版本的那個「起」的己怎麼沒變成巳？
按照傳承字形的標準：https://github.com/ichitenfont/inheritedglyphs
「起」的右上邊是「巳」，不從「已」或「己」。
還有部分沒變，後續能更新嗎？

**Comment by NightFurySL2001** [comment]
好的，已记录在案，感谢提报。还有其他部分吗？

**Comment by ghost** [comment]
component_of_recom_inherited_glyphs-1.35.pdf
裡面的標準可以按照一下。

**Comment by NightFurySL2001** [comment]
本人确实是依照传承字形标准进行修改。部分字形目前判断为无法配合原字体风格（如横点/直点/出头彐），部分是修改后结构无法平衡（如次、产），剩下则是待探讨是否应该修改（如即飠尚关平半乎）。目前 1.000 版本将会是优先修改急需适配的字形（如骨麦真具直艹等繁体常用部件），如果您觉得哪些是必要且遗漏（如起）的部件可以先提出进行优化。

**Comment by ghost** [comment]
謝謝！

**Comment by NightFurySL2001** [comment]
（还没修好的bug请别关闭，会影响记录追踪）

**Comment by ghost** [comment]
為的字形仍舊是陸標。

**Comment by ghost** [comment]
熵的右邊應該是商！你忘了改啦！

**Comment by ghost** [comment]
但有少部分缺字，像是「噁」等等

**Comment by NightFurySL2001** [comment]
目前繁体补字范围是Big5常用字 5041 （包含台湾教育部字表 4808），今晚更新时补上「噁」。

**Comment by NightFurySL2001** [comment]
Ver 1.100 版已经解决，感谢提报！
